<?php $this->form->prepare()?>
<div class="header_cont">
    <div class="title"><?=$this->translate(ucfirst($this->action)." a user")?></div>
</div>
<div class="body_cont">
    <?=$this->form()->openTag($this->form)?>
    <table class="list_table" width="400" cellpadding="5" cellspacing="0">
        <tr>
            <td><label><?=$this->translate($this->form->get('uname')->getLabel())?></label></td>
            <td>
                <?=$this->formInput($this->form->get('uname'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('uname'))?>
                </div>
            </td>
        </tr>
        <tr>
        <td><label><?=$this->translate($this->form->get('email')->getLabel())?></label></td>
        <td>
                <?=$this->formInput($this->form->get('email'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('email'))?>
                </div>
            </td>
        </tr>
        <tr>
            <td><label><?=$this->translate($this->form->get('role')->getLabel())?></label></td>
            <td>
                <?=$this->formSelect($this->form->get('role'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('role'))?>
                </div>
            </td>
        </tr>
        <?php if($this->action == 'edit'): ?>
            <tr>
                <td colspan="2"><?=$this->translate('Fill in the following if only if you want to change password')?>:</td>
            </tr>
        <?php endif; ?>
        <tr>
            <td><label><?=$this->translate($this->form->get('password')->getLabel())?></label></td>
            <td>
                <?=$this->formInput($this->form->get('password'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('password'))?>
                </div>
            </td>
        </tr>
        <tr>
            <td><label><?=$this->translate($this->form->get('password_repeat')->getLabel())?></label></td>
            <td>
                <?=$this->formInput($this->form->get('password_repeat'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('password_repeat'))?>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button class="btn btn-primary btn-xs" name="categ_form"><?=$this->translate(ucfirst($this->action))?></button>
                <small> or <a href="<?=$this->langUrl('admin/default', [
                        'controller' => 'user',
                        'page' => $this->page,
                    ])?>">Cancel</a></small>
            </td>
        </tr>
    </table>
    <?=$this->form()->closeTag()?>
    <div style="height:100px;">&nbsp;</div>
</div>