<div class="header_cont">
    <div class="title"><?=$this->translate('Users')?></div>
    <div style="float:right;">
        <button type="button" id="add_button" class="btn btn-primary btn-xs"><?=$this->translate('New')?></button>
    </div>
</div>
<div class="body_cont">
    <table class="list_table" width="100%" cellpadding="5" cellspacing="0">
        <tr>
            <th width="20">#</th>
            <th><?=$this->translate('User Name')?></th>
            <th><?=$this->translate('Email')?></th>
            <th width="70"><?=$this->translate('Role')?></th>
            <th width="70"><?=$this->translate('Registered')?></th>
            <th width="70"><?=$this->translate('Action')?></th>
        </tr>
        <?php foreach($this->users as $user): ?>
            <tr>
                <td><?=$user->getId()?></td>
                <td><?=$user->getUname()?></td>
                <td><?=$user->getEmail()?></td>
                <td><?=$user->getRoleName()?></td>
                <td><?=$user->getRegDate('m-d-Y')?></td>
                <td>
                    <a class="img" href="<?=$this->langUrl('admin/default', array(
                        'controller' => 'user',
                        'action' => 'edit',
                        'id' => $user->getId(),
                        'page' => $this->page,
                    ))?>">
                        <img src="<?=$this->basePath()?>/img/admin/edit.gif" title="<?=$this->translate('edit')?>" />
                    </a>
                    <a class="img del_button" href="#" data-href="<?=$this->langUrl('admin/default', [
                        'controller' => 'user',
                        'action' => 'delete',
                        'id' => $user->getId(),
                        'page' => $this->page,
                    ])?>">
                        <img src="<?=$this->basePath()?>/img/admin/delete.gif" title="<?=$this->translate('delete')?>" />
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <?=$this->paginationControl($this->users, 'Sliding', 'paginator/sliding', [
        'route' => 'admin/default', 'controller' => 'user'])?>
</div>
<script type="text/javascript">
    $('#add_button').click(function(){
        location.href='<?=$this->langUrl('admin/default', [
        'controller' => 'user',
        'action' => 'add',
        'page' => $this->page,
        ])?>';
    });
    $('.del_button').click(function(){
        if(confirm('<?=$this->translate('Are you sure you want to delete this user?')?>')){
            location.href=this.dataset.href;
        }
        return false;
    });
</script>