<div class="header_cont">
    <div class="title" data-bind="text: title()"></div>
    <div data-bind="visible: action() == 'list'" style="float:right;">
        <a type="button" href="#add" class="btn btn-primary btn-xs"><?=$this->translate('New')?></a>
    </div>
</div>
<div class="body_cont">
    <div data-bind="visible: action() == 'list'">
        <table class="list_table" width="100%" cellpadding="5" cellspacing="0">
            <thead>
            <tr>
                <th width="20">#</th>
                <th><?=$this->translate('User Name')?></th>
                <th><?=$this->translate('Email')?></th>
                <th width="100"><?=$this->translate('Role')?></th>
                <th width="100"><?=$this->translate('Registered')?></th>
                <th width="70"><?=$this->translate('Action')?></th>
            </tr>
            </thead>
            <tbody data-bind="visible: hasRecords() === true, foreach: listData">
            <tr>
                <td data-bind="text: id"></td>
                <td>
                    <span data-bind="text: uname"></span>
                    <span data-bind="if: $root.various().identity_id == id">
                        <span style="font-weight: bold">(<?=$this->translate('You')?>)</span>
                    </span>
                </td>
                <td data-bind="text: email"></td>
                <td data-bind="text: role"></td>
                <td data-bind="text: reg_date"></td>
                <td>
                    <a class="img" data-bind="attr: {href: '#edit/'+id}">
                        <img src="<?=$this->basePath()?>/img/admin/edit.gif" title="<?=$this->translate('edit')?>" />
                    </a>
                    <span data-bind="if: $root.various().identity_id != id">
                        <a class="img del_button" href="#" data-bind="click: function(data, event){ clickDelete(id); }">
                            <img src="<?=$this->basePath()?>/img/admin/delete.gif" title="<?=$this->translate('delete')?>" />
                        </a>
                        <form method="POST" data-bind="attr: {action: '#delete/'+id}">
                            <input type="hidden" name="id" data-bind="value: id" />
                            <input type="submit" data-bind="attr: {id: 'del_'+id}, visible: false" />
                        </form>
                    </span>
                </td>
            </tr>
            </tbody>
        </table>
        <span data-bind="html: paginator"></span>
    </div>
    <!--edit/add action -->
    <span data-bind="visible: action() == 'edit' || action() == 'add', dynamicHtml: form()"></span>
</div>
<span style="display:none" id="url"><?=$this->langUrl("admin/user")?></span>
<script type="text/javascript" src="<?=$this->basePath()?>/js/admin/rest.js"></script>
<script type="text/javascript">
    function clickDelete(id){
        if(confirm('<?=$this->translate('Are you sure you want to delete this user?')?>')){
            document.getElementById('del_'+id).click();
        }
        return false;
    }
</script>