<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->

<?php if ($this->pageCount): ?>
    <div class="paginationControl">
        <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
        of <?php echo $this->totalItemCount; ?>

        <!-- First page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->langUrl($this->route, array('id' => $this->id, 'page' => $this->first)); ?>">
                <?=$this->translate('First')?>
            </a> |
        <?php else: ?>
            <span class="disabled"><?=$this->translate('First')?></span> |
        <?php endif; ?>

        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->langUrl($this->route, array('id' => $this->id, 'page' => $this->previous)); ?>">
                &lt; <?=$this->translate('Previous')?>
            </a> |
        <?php else: ?>
            <span class="disabled">&lt; <?=$this->translate('Previous')?></span> |
        <?php endif; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->langUrl($this->route, array('id' => $this->id, 'page' => $this->next)); ?>">
        <?=$this->translate('Next')?> &gt;
            </a> |
        <?php else: ?>
            <span class="disabled"><?=$this->translate('Next')?> &gt;</span> |
        <?php endif; ?>

        <!-- Last page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->langUrl($this->route, array('id' => $this->id, 'page' => $this->last)); ?>">
        <?=$this->translate('Last')?>
            </a>
        <?php else: ?>
            <span class="disabled"><?=$this->translate('Last')?></span>
        <?php endif; ?>

    </div>
<?php endif; ?>