<?php
$this->form->prepare();
$this->form->setAttribute('action', '#'.$this->action.($this->action == 'edit' ? '/'.$this->id : ''));
?>
<?=$this->form()->openTag($this->form)?>
<table class="list_table" width="400" cellpadding="5" cellspacing="0">
    <?php foreach($this->form->get('content')->getFieldsets() as $fieldset):?>
        <tr>
            <td>
                <?php if(!isset($labelled)): ?>
                    <label><?=$this->translate($this->form->get('content')->getFieldsets()[0]->getElements()['title']->getLabel())?>:</label>
                <?php $labelled = true; endif; ?>
            </td>
            <td>
                <?=$this->formInput($fieldset->getElements()['title'])?>
                <?php $lang = $fieldset->getObject()->getLang()?>
                <img src="<?=$this->corePath().'/img/flags/'.$lang->getIsoCode()?>.png" title="<?=$lang->getName()?>" />
                <?php if($lang->isDefault()):?>(<?=$this->translate('default')?>)<?php endif; ?>
                <div class="form-error">
                    <?=$this->formElementErrors($fieldset->getElements()['title'])?>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <td><label><?=$this->translate($this->form->get('sort')->getLabel())?></label></td>
        <td>
            <?=$this->formInput($this->form->get('sort'))?>
            <div class="form-error">
                <?=$this->formElementErrors($this->form->get('sort'))?>
            </div>
        </td>
    </tr>
    <tr>
        <td><?=$this->translate('Parent category')?>:</td>
        <td>
            <?=$this->formSelect($this->form->get('parent_id'))?>
            <div class="form-error">
                <?=$this->formElementErrors($this->form->get('parent_id'))?>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <?=$this->formInput($this->form->get('category_csrf'))?>
            <button class="btn btn-primary btn-xs" name="categ_form"><?=$this->translate('Submit')?></button>
            <small><a data-bind="attr: {href: '#'+parentID()+'/'+page()}"><?=$this->translate('Cancel')?></a></small>
        </td>
    </tr>
</table>
<?=$this->form()->closeTag()?>
<div style="height:100px;">&nbsp;</div>