<?php
use Application\Service\Invokable\Misc;
$this->form->prepare();
?>
<div class="header_cont">
    <div class="title"><?=$this->translate($this->action." a page")?></div>
</div>
<div class="body_cont">
    <?=$this->form()->openTag($this->form)?>
    <div class="tabs">
        <ul>
            <li><a href="#tabs-1"><?=$this->translate('Content')?></a></li>
            <li><a href="#tabs-2"><?=$this->translate('Meta tags')?></a></li>
        </ul>
        <div id="tabs-1">
            <div class="tabs">
                <ul>
                    <?php foreach(Misc::getActiveLangs() as $lang):?>
                        <li>
                            <a href="#tabs-1-<?=$lang->getId()?>">
                                <img src="<?=$this->basePath().'/img/flags/'.$lang->getIsoCode()?>.png" />
                                <?=$lang->getIsoCode()?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <?php foreach($this->form->getFieldsets()['content']->getFieldsets() as $fieldset): ?>
                    <div id="tabs-1-<?=$fieldset->getObject()->getLang()->getId()?>">
                        <?php foreach($fieldset->getElements() as $element): ?>
                            <div class="form-group">
                                <label><?=$this->translate($element->getLabel())?>:</label>
                                <?=$this->formElement($element)?>
                                <div class="form-error"><?=$this->formElementErrors($element)?></div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="form-group">&nbsp;</div>
            <div class="row form-group">
                <label class="col-md-2"><?=$this->translate($this->form->get('category')->getLabel())?>:</label>
                <div class="col-md-10"><?=$this->formElement($this->form->get('category'))?></div>
            </div>
            <div class="row form-group">
                <label class="col-md-2"><?=$this->translate($this->form->get('sort')->getLabel())?>:</label>
                <div class="col-md-10"><?=$this->formInput($this->form->get('sort'))?></div>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('sort'))?>
                </div>
            </div>
            <hr />
            <div class="row form-group">
                <label class="col-md-2"><?=$this->translate($this->form->get('listingImage')->getLabel())?></label>
                <div class="col-md-10"><?=$this->formFile($this->form->get('listingImage'))?></div>
                <div class="col-md-12 form-error">
                    <?=$this->formElementErrors($this->form->get('listingImage'))?>
                </div>
                <?php if($this->image):?>
                    <div class="col-md-12">
                        <img style="width:100px;" src="<?=$this->basePath().$this->image?>" />
                        <?=$this->formCheckbox($this->form->get('image_remove'))?> <label><?=$this->translate($this->form->get('image_remove')->getLabel())?></label>
                    </div>
                <?php endif?>
            </div>
        </div>
        <div id="tabs-2">
            <div class="tabs">
                <ul>
                    <?php foreach(Misc::getActiveLangs() as $lang):?>
                        <li>
                            <a href="#tabs-2-<?=$lang->getId()?>">
                                <img src="<?=$this->basePath().'/img/flags/'.$lang->getIsoCode()?>.png" />
                                <?=$lang->getIsoCode()?>
                            </a>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <?php foreach($this->form->getFieldsets()['metadata']->getFieldsets() as $fieldset): ?>
                    <div id="tabs-2-<?=$fieldset->getObject()->getLang()->getId()?>">
                        <?php foreach($fieldset->getElements() as $element): ?>
                            <div class="form-group">
                                <label><?=$this->translate($element->getLabel())?>:</label>
                                <?=$this->formElement($element)?>
                                <div class="form-error"><?=$this->formElementErrors($element)?></div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div class="form-group">&nbsp;</div>
    <div class="form-group">
        <button class="btn btn-primary btn-xs" name="categ_form"><?=$this->translate('Submit')?></button>
        <small> or <a href="<?=$this->langUrl('admin/listing', [
                'id' => $this->filter,
                'page' => $this->page,
            ])?>">Cancel</a></small>
        <?=$this->form()->closeTag()?>
        <div style="height:100px;">&nbsp;</div>
    </div>
</div>
<script type="text/javascript">
    $('.tabs').tabs();
</script>