<div class="panel-heading"><?=$this->translate('Dashboard')?></div>
<div class="panel-body">
    <div class="icons">
        <a class="btn btn-default btn-lg dashboard_buttons" href="<?=$this->langUrl('admin/rest', ['controller' => 'listing', 'action' => 'list'])?>" title="<?=$this->translate('Pages')?>">
            <span class="glyphicon glyphicon-font" aria-hidden="true"></span>
        </a>
        <br />
        <?=$this->translate('Pages')?>
    </div>
    <div class="icons">
        <a class="btn btn-default btn-lg dashboard_buttons" href="<?=$this->langUrl('admin/rest', ['controller' => 'category', 'action' => 'list'])?>" title="<?=$this->translate('Categories')?>">
            <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
        </a>
        <br />
        <?=$this->translate('Categories')?>
    </div>
    <div class="icons">
        <a class="btn btn-default btn-lg dashboard_buttons" href="<?=$this->langUrl('admin/rest', ['controller' => 'language', 'action' => 'list'])?>" title="<?=$this->translate('Languages')?>">
            <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
        </a>
        <br />
        <?=$this->translate('Languages')?>
    </div>
    <div class="icons">
        <a class="btn btn-default btn-lg dashboard_buttons" href="<?=$this->langUrl('admin/rest', ['controller' => 'user', 'action'=>'list'])?>" title="<?=$this->translate('Users')?>">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        </a>
        <br />
        <?=$this->translate('Users')?>
    </div>
    <div class="icons">
        <a class="btn btn-default btn-lg dashboard_buttons" href="<?=$this->langUrl('admin/rest', [
            'controller' => 'user',
            'action' => 'list',
        ], ['fragment' => 'edit/'.$auth->getIdentity()->getId()])?>" title="<?=$this->translate('Account settings')?>">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
        </a>
        <br />
        <?=$this->translate('Account settings')?>
    </div>
    <div style="height:300px;">&nbsp;</div>
</div>