<?php
use Application\Service\Invokable;
$auth = new \Zend\Authentication\AuthenticationService();
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <?=$this->headTitle($this->translate('Administration panel'))."\n"?>
    <?=$this->headLink()
        ->prependStylesheet($this->basePath().'/css/admin/style.css')
        ->prependStylesheet($this->basePath().'/js/admin/jquery-ui-1.11.4.custom/jquery-ui.min.css')
        ->prependStylesheet($this->basePath() .'/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    ."\n"
    ?>
    <?=$this->headScript()
        ->prependFile($this->basePath() . '/js/admin/script.js')
        ->prependFile($this->basePath() . '/js/admin/jquery-ui-1.11.4.custom/jquery-ui.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath().'/js/jquery-2.1.4.min.js')
    ."\n"
    ?>

    <script type="text/javascript">
        window.onload = function(){
            handleMenu();
        }
    </script>
</head>
<body>
    <div id="main">
        <div class="header">
            <div class="col-md-3" style="text-transform: uppercase; margin-top: 11px;">
                <a href="<?=$this->langUrl('admin')?>"><?=$this->translate('Admin panel')?></a>
            </div>
            <div class="col-md-9" style="padding-right: 0px;">
                <div class="col-md-12" style="text-align: right">
                    <?php if($auth->hasIdentity()):?>
                        <small><?=$this->translate('Logged as').' ['.$auth->getIdentity()->getUname()?>]</small>
                    <?php endif; ?>
                </div>
                <div class="col-md-2" style="float: right;width: 72px;">
                    <a href="<?=$this->langUrl('admin/default', ['controller' => 'log', 'action' => 'out'])?>"><?=$this->translate('Log out')?></a>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div id="menu">
            <ul>
                <li><a rel="subMenu0" href="Javascript:void(0)" ><?=$this->translate('Content')?> |</a>
                    <div id="subMenu0">
                        <a href="<?=$this->langUrl('admin/category')?>"><?=$this->translate('Categories')?></a>
                        <a href="<?=$this->langUrl('admin/listing')?>"><?=$this->translate('Pages')?></a>
                    </div>
                </li>
                <li><a rel="subMenu2" href="Javascript:void(0)"><?=$this->translate('Administration')?>&nbsp;|</a>
                    <div id="subMenu2">
                        <a href="<?=$this->langUrl('admin/default', ['controller'=>'language'])?>"><?=$this->translate('Languages')?></a>
                        <a href="<?=$this->langUrl('admin/default', ['controller'=>'user'])?>"><?=$this->translate('Users')?></a>
                        <a href="<?=$this->langUrl('admin/default', [
                            'controller'=>'user',
                            'action' => 'edit',
                            'id' => $auth->getIdentity()->getId()
                        ], ['query' => ['account_settings' => 1]])?>"><?=$this->translate('Account settings')?></a>
                    </div>
                </li>
            </ul>
            <ul style="float:right;">
                <li class="lang">
                    <span class="text lang">
                        <select name="lang" onChange="goToHref(this.value)">
                            <?php foreach(Invokable\Misc::getActiveLangsArray() as $lang):
                                $selected = Invokable\Misc::getCurrentLanguage()->getId() == $lang['id'] ? 'selected="selected"' : '';?>
                                <option value="<?=$this->url($this->route != 'admin' ? $this->route : 'admin/default', [
                                    'controller' => $this->controller,
                                    'action' => $this->action,
                                    'id' => $this->id,
                                    'page' => $this->page,
                                    'lang' => $lang['isoCode'] != Invokable\Misc::getDefaultLanguage()->getIsoCode() ? $lang['isoCode'] : null,//if the language is the default, then do not append with language route
                                ])?>" <?=$selected?>>
                                    <?=$lang['name']?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </span>
                </li>
            </ul>
        </div>
        <div class="mbody">
            <div class="content">
                <div class="messages">
                    <?php foreach (array('error', 'success', 'info', 'default') as $namespace):
                        //check for error messages
                        $plugin = $this->flashMessenger()->getPluginFlashMessenger();
                        if($plugin->getCurrentErrorMessages()){
                            echo $this->flashMessenger()->renderCurrent($namespace, array('alert', 'alert-dismissible', 'alert-danger'));
                            $plugin->clearCurrentMessages('error');
                        }
                        $style = $namespace != 'error' ? array('alert', 'alert-dismissible', 'alert-'.$namespace) :
                            array('alert', 'alert-dismissible', 'alert-danger');
                        echo $this->flashMessenger()->render($namespace, $style);
                    endforeach; ?>
                </div>
                <div class="container">
                    <?=$this->content?>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
        <footer class="footer">
            &copy; <?=date('Y')?> <a href="https://github.com/veniva/zcms">ZCMS - A light weight CMS</a>, released under the <a target="_blank" href="http://www.gnu.org/licenses/gpl-3.0.en.html">GNU/GPL 3.0 licence</a>
        </footer>
        <div class="clearfix"></div>
    </div>
</body>
</html>
