<?php use Application\Service\Invokable; ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <?=$this->headTitle($this->translate('Administration panel'))."\n"?>
    <?=$this->headLink()
        ->prependStylesheet($this->basePath().'/css/admin/style.css')
        ->prependStylesheet($this->basePath().'/js/admin/jquery-ui-1.11.4.custom/jquery-ui.min.css')
        ->prependStylesheet($this->basePath() .'/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    ."\n"
    ?>
    <?=$this->headScript()
        ->prependFile($this->basePath() . '/js/admin/script.js')
        ->prependFile($this->basePath() . '/js/admin/jquery-ui-1.11.4.custom/jquery-ui.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath().'/js/jquery-2.1.4.min.js')
    ."\n"
    ?>

    <script type="text/javascript">
        window.onload = function(){
            handleMenu();
        }
    </script>
</head>
<body>
    <div id="main">
        <div class="header">
            <div class="col-md-2" style="text-transform: uppercase"><a href="<?=$this->langUrl('admin')?>"><?=$this->translate('Admin panel')?></a></div>
            <div class="col-md-1" style="float: right;"><a href="<?=$this->langUrl('admin/default', ['controller' => 'log', 'action' => 'out'])?>"><?=$this->translate('Log out')?></a></div>
            <div class="clearfix"></div>
        </div>
        <div id="menu">
            <ul>
                <li><a rel="subMenu0" href="Javascript:void(0)" ><?=$this->translate('Content')?> |</a>
                    <div id="subMenu0">
                        <a href="<?=$this->langUrl('admin/category')?>"><?=$this->translate('Categories')?></a>
                        <a href="<?=$this->langUrl('admin/listing')?>"><?=$this->translate('Pages')?></a>
                    </div>
                </li>
                <li><a rel="subMenu2" href="Javascript:void(0)"><?=$this->translate('Administration')?>&nbsp;|</a>
                    <div id="subMenu2">
                        <a href="<?=$this->langUrl('admin/default', ['controller'=>'language'])?>"><?=$this->translate('Languages')?></a>
                        <a href=""><?=$this->translate('Users')?></a>
                        <a href=""><?=$this->translate('Change password')?></a>
                        <a href=""><?=$this->translate('Change email')?></a>
                    </div>
                </li>
            </ul>
            <ul style="float:right;">
                <li class="lang">
                    <span class="text lang">
                        <select name="lang" onChange="goToHref(this.value)">
                            <?php foreach(Invokable\Misc::getActiveLangsArray() as $lang):
                                $selected = Invokable\Misc::getCurrentLang()->getId() == $lang['id'] ? 'selected="selected"' : '';?>
                                <option value="<?=$this->url($this->route != 'admin' ? $this->route : 'admin/default', [
                                    'controller' => $this->controller,
                                    'action' => $this->action,
                                    'id' => $this->id,
                                    'page' => $this->page,
                                    'lang' => $lang['isoCode']])?>" <?=$selected?>><?=$lang['name']?></option>
                            <?php endforeach; ?>
                        </select>
                    </span>
                </li>
            </ul>
        </div>
        <div class="mbody">
            <div class="content">
                <div class="messages">
                    <?php foreach (array('error', 'success', 'info', 'default') as $namespace):
                        //check for error messages
                        $plugin = $this->flashMessenger()->getPluginFlashMessenger();
                        if($plugin->getCurrentErrorMessages()){
                            echo $this->flashMessenger()->renderCurrent($namespace, array('alert', 'alert-dismissible', 'alert-danger'));
                            $plugin->clearCurrentMessages('error');
                        }
                        $style = $namespace != 'error' ? array('alert', 'alert-dismissible', 'alert-'.$namespace) :
                            array('alert', 'alert-dismissible', 'alert-danger');
                        echo $this->flashMessenger()->render($namespace, $style);//V_TODO - use $this->flashmessenger()->renderCurrent() to show not only redirect msgs., also make sure not to display those twice in case of redirection
                    endforeach; ?>
                </div>
                <div class="container">
                    <?=$this->content?>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</body>
</html>
