<?php $this->layout('admin/login');//change the default layout to the login layout

$form  = $this->form;
$form->prepare();
$email = $form->get('email');
$errors = $this->formElementErrors($email);
?>
<div class="messages">
    <?php foreach (array('error', 'success', 'info', 'default') as $namespace):
        $flashMessages = $this->flashmessenger()->render($namespace);
        $namespace = $namespace == 'error' ? 'danger' : $namespace;/*adjust bootstrap to ZF2*/
        if (!empty($flashMessages)):?>
            <div class="alert alert-<?=$namespace?>" role="alert">
                <?= $flashMessages ?>
            </div>
        <?php endif;
    endforeach; ?>
    <?php if($errors):?>
        <div class="alert alert-danger" role="alert">
            <?=$errors?>
        </div>
    <?php endif;?>
</div>

<div class="login">
    <div class="login_font" style="margin-bottom:20px;"> <?=$this->translate('Generate new password')?></div>
    <?=$this->form()->openTag($form)?>
    <div class="uname"><?=$this->translate($email->getLabel())?>:</div>
    <div class="uform">
        <?=$this->formInput($email)?>
    </div>
    <div class="uform">
        <input type="submit" name="submit" value="<?=$this->translate('Reset password')?>" />
    </div>
    <?=$this->form()->closeTag()?>
    <div class="forgotten">
        <a href="<?=$this->langUrl('admin/default', ['controller' => 'log', 'action' => 'in'])?>"><?=$this->translate('Back to login')?></a>
    </div>
</div>