<?php $this->layout('admin/login');
$this->form->prepare();
?>
<div class="messages">
    <?php foreach (array('error', 'success', 'info', 'default') as $namespace):
        $flashMessages = $this->flashmessenger()->render($namespace);
        $namespace = $namespace == 'error' ? 'danger' : $namespace;/*adjust bootstrap to ZF2*/
        if (!empty($flashMessages)):?>
            <div class="alert alert-<?=$namespace?>" role="alert">
                <?= $flashMessages ?>
            </div>
        <?php endif;
    endforeach; ?>
</div>

<div class="login" style="width:400px">
    <?=$this->form()->openTag($this->form)?>
    <table class="table" width="300" cellpadding="5" cellspacing="5">
        <tr>
            <td><label><?=$this->translate($this->form->get('uname')->getLabel())?></label></td>
            <td>
                <?=$this->formInput($this->form->get('uname'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('uname'))?>
                </div>
            </td>
        </tr>
        <tr>
            <td><label><?=$this->translate($this->form->get('email')->getLabel())?></label></td>
            <td>
                <?=$this->formInput($this->form->get('email'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('email'))?>
                </div>
            </td>
        </tr>
        <tr>
            <td><label><?=$this->translate('Language name')?></label></td>
            <td>
                <?=$this->formInput($this->form->get('language_name'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('language_name'))?>
                </div>
            </td>
        </tr>
        <tr>
            <td><label><?=$this->translate('Language code')?></label></td>
            <td>
                <?=$this->formSelect($this->form->get('isoCode'))?>
                <img id="flag" src="<?=$this->basePath()?>/img/flags/<?=$this->flagCode?>.png" />
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('isoCode'))?>
                </div>
            </td>
        </tr>
        <tr>
            <td><label><?=$this->translate($this->form->get('password_fields')->get('password')->getLabel())?></label></td>
            <td>
                <?=$this->formInput($this->form->get('password_fields')->get('password'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('password_fields')->get('password'))?>
                </div>
            </td>
        </tr>
        <tr>
            <td><label><?=$this->translate($this->form->get('password_fields')->get('password_repeat')->getLabel())?></label></td>
            <td>
                <?=$this->formInput($this->form->get('password_fields')->get('password_repeat'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('password_fields')->get('password_repeat'))?>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <?=$this->formSubmit($this->form->get('submit'))?>
            </td>
        </tr>
    </table>
    <?=$this->form()->closeTag()?>
</div>
<script type="text/javascript">
    var $flagImg = $(document.getElementById('flag'));
    $flagImg.attr('src', function(){
        <?php if($this->flagCode):?>
            return "<?=$this->basePath()?>/img/flags/<?=$this->flagCode?>.png";
        <?php else: ?>
            return "<?=$this->basePath()?>/img/pixel-trans.gif";
        <?php endif; ?>
    });

    $(document.getElementById('flags_select')).change(function(){
        var imgName = (this.value.length > 0) ? 'flags/'+this.value+'.png' : 'pixel-trans.gif'
        $flagImg.attr('src', "<?=$this->basePath()?>/img/"+imgName)
    });
</script>