<?php $this->layout('admin/login');
$this->form->setAttribute('class', 'form-horizontal');
$this->form->prepare();
foreach($form->getElements() as $element){
    if($element->getAttribute('type') != 'submit'){
        $element->setAttribute('class', 'form-control');
    }else{
        $element->setAttribute('class', 'btn btn-default');
    }
}
foreach($this->form->getFieldsets() as $fieldset){
    foreach($fieldset->getElements() as $element){
        $element->setAttribute('class', 'form-control');
    }
}
?>
<div class="messages">
    <?php foreach (array('error', 'success', 'info', 'default') as $namespace):
        $flashMessages = $this->flashmessenger()->render($namespace);
        $namespace = $namespace == 'error' ? 'danger' : $namespace;/*adjust bootstrap to ZF2*/
        if (!empty($flashMessages)):?>
            <div class="alert alert-<?=$namespace?>" role="alert">
                <?= $flashMessages ?>
            </div>
        <?php endif;
    endforeach; ?>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Initial setup</div>
    <div class="panel-body">
        <?=$this->form()->openTag($this->form)?>
        <div class="form-group">
            <label class="form-label col-md-4"><?=$this->translate($this->form->get('uname')->getLabel())?></label>
            <div class="col-md-8">
                <?=$this->formInput($this->form->get('uname'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('uname'))?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="form-label col-md-4"><?=$this->translate($this->form->get('email')->getLabel())?></label>
            <div class="col-md-8">
                <?=$this->formInput($this->form->get('email'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('email'))?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="form-label col-md-4"><?=$this->translate('Language name')?></label>
            <div class="col-md-8">
                <?=$this->formInput($this->form->get('language_name'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('language_name'))?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="form-label col-md-4"><?=$this->translate('Language code')?></label>
            <div class="col-md-6">
                <?=$this->formSelect($this->form->get('isoCode'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('isoCode'))?>
                </div>
            </div>
            <div class="col-md-2"><img id="flag" src="<?=$this->basePath()?>/img/flags/<?=$this->flagCode?>.png" /></div>
        </div>
        <div class="form-group">
            <label class="form-label col-md-4"><?=$this->translate($this->form->get('password_fields')->get('password')->getLabel())?></label>
            <div class="col-md-8">
                <?=$this->formInput($this->form->get('password_fields')->get('password'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('password_fields')->get('password'))?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="form-label col-md-4"><?=$this->translate($this->form->get('password_fields')->get('password_repeat')->getLabel())?></label>
            <div class="col-md-8">
                <?=$this->formInput($this->form->get('password_fields')->get('password_repeat'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('password_fields')->get('password_repeat'))?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-4">
                <?=$this->formSubmit($this->form->get('submit'))?>
            </div>
        </div>
        <?=$this->form()->closeTag()?>
    </div>
</div>
<script type="text/javascript">
    var $flagImg = $(document.getElementById('flag'));
    $flagImg.attr('src', function(){
        <?php if($this->flagCode):?>
            return "<?=$this->basePath()?>/img/flags/<?=$this->flagCode?>.png";
        <?php else: ?>
            return "<?=$this->basePath()?>/img/pixel-trans.gif";
        <?php endif; ?>
    });

    $(document.getElementById('flags_select')).change(function(){
        var imgName = (this.value.length > 0) ? 'flags/'+this.value+'.png' : 'pixel-trans.gif'
        $flagImg.attr('src', "<?=$this->basePath()?>/img/"+imgName)
    });
</script>