<?php $this->layout('admin/login');//change the default layout to the login layout

$form  = $this->form;
$form->prepare();
$form->setAttribute('class', 'form-horizontal');
$this->form->get('password_fields')->get('password')->setAttribute('class', 'form-control');
$this->form->get('password_fields')->get('password_repeat')->setAttribute('class', 'form-control');
?>

<div class="messages">
    <?php foreach (array('error', 'success', 'info', 'default') as $namespace):
        $flashMessages = $this->flashmessenger()->render($namespace);
        $namespace = $namespace == 'error' ? 'danger' : $namespace;/*adjust bootstrap to ZF2*/
        if (!empty($flashMessages)):?>
            <div class="alert alert-<?=$namespace?>" role="alert">
                <?= $flashMessages ?>
            </div>
        <?php endif;
    endforeach; ?>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <?=$this->translate('Reset password')?>
    </div>
    <div class="panel-body">
        <?=$this->form()->openTag($form)?>
        <div class="form-group">
            <label class="control-label col-md-4">
                <?=$this->translate($form->get('password_fields')->get('password')->getLabel())?>:
            </label>
            <div class="col-md-8">
                <?=$this->formInput($form->get('password_fields')->get('password'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('password_fields')->get('password'));?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-4">
                <?=$this->translate($form->get('password_fields')->get('password_repeat')->getLabel())?>:
            </label>
            <div class="col-md-8">
                <?=$this->formInput($form->get('password_fields')->get('password_repeat'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('password_fields')->get('password_repeat'));?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-4">
                <input class="btn btn-default" type="submit" name="submit" value="<?=$this->translate('Edit')?>" />
                <a class="btn btn-link forgotten_link" href="<?=$this->langUrl('admin/default', ['controller' => 'log', 'action' => 'in'])?>"><?=$this->translate('Back to login')?></a>
            </div>
        </div>
        <?=$this->form()->closeTag()?>
    </div>
</div>