<?php $this->layout('admin/login');//change the default layout to the login layout

$form  = $this->form;
$form->prepare();
?>

<div class="messages">
    <?php foreach (array('error', 'success', 'info', 'default') as $namespace):
        $flashMessages = $this->flashmessenger()->render($namespace);
        $namespace = $namespace == 'error' ? 'danger' : $namespace;/*adjust bootstrap to ZF2*/
        if (!empty($flashMessages)):?>
            <div class="alert alert-<?=$namespace?>" role="alert">
                <?= $flashMessages ?>
            </div>
        <?php endif;
    endforeach; ?>
</div>

<div class="login">
    <div class="login_font" style="margin-bottom:20px;"> <?=$this->translate('Reset password')?></div>
    <?=$this->form()->openTag($form)?>
    <div class="uname"><?=$this->translate($form->get('password_fields')->get('password')->getLabel())?>:</div>
    <div class="uform">
        <?=$this->formInput($form->get('password_fields')->get('password'))?>
        <div class="form-error">
            <?=$this->formElementErrors($this->form->get('password_fields')->get('password'));?>
        </div>
    </div>
    <div class="uname"><?=$this->translate($form->get('password_fields')->get('password_repeat')->getLabel())?>:</div>
    <div class="uform">
        <?=$this->formInput($form->get('password_fields')->get('password_repeat'))?>
        <div class="form-error">
            <?=$this->formElementErrors($this->form->get('password_fields')->get('password_repeat'));?>
        </div>
    </div>
    <div class="uform">
        <input type="submit" name="submit" value="<?=$this->translate('Edit')?>" />
    </div>
    <?=$this->form()->closeTag()?>
    <div class="forgotten">
        <a href="<?=$this->langUrl('admin/default', ['controller' => 'log', 'action' => 'in'])?>"><?=$this->translate('Back to login')?></a>
    </div>
</div>