<select name="lang" onChange="goToHref(this.value)">
    <?php foreach($this->languages->getActiveLanguages() as $lang):
        $selected = $this->languages->getCurrentLanguage()->getId() == $lang->getId() ? 'selected="selected"' : '';?>
        <option value="<?=$this->url(!empty($this->route) && $this->route != 'admin' ? $this->route : 'admin/default', [
            'controller' => $this->controller,
            'action' => $this->action,
            'id' => $this->id,
            'page' => $this->page,
            'lang' => $lang->getIsoCode() != $this->languages->getDefaultLanguage()->getIsoCode() ? $lang->getIsoCode() : null,//if the language is the default, then do not append with language route
        ], ['query' => $this->queryString])?>" <?=$selected?>>
            <?=$lang->getName()?>
        </option>
    <?php endforeach; ?>
</select>