<?php
$auth = new \Zend\Authentication\AuthenticationService();
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <?=$this->headTitle($this->translate('Administration panel'))."\n"?>
    <?=$this->headLink()
        ->appendStylesheet($this->corePath() . '/css/bootstrap.min.css')
        ->appendStylesheet($this->corePath() .'/css/bootstrap-theme.min.css')
        ->appendStylesheet($this->corePath().'/js/admin/jquery-ui-1.11.4.custom/jquery-ui.min.css')
        ->appendStylesheet($this->corePath().'/css/bootstrap-extend.css')
        ->appendStylesheet($this->corePath().'/css/admin/style.css')
    ."\n"
    ?>
    <?=$this->headScript()
        ->appendFile($this->corePath().'/js/jquery-2.1.4.min.js')
        ->appendFile($this->corePath() . '/js/bootstrap.min.js')
        ->appendFile($this->corePath() . '/js/admin/jquery-ui-1.11.4.custom/jquery-ui.min.js')
        ->appendFile($this->corePath() . '/js/sammy.js')
        ->appendFile($this->corePath() . '/bower_components/knockout/dist/knockout.js')
        ->appendFile($this->corePath() . '/bower_components/knockout-file-bindings/knockout-file-bindings.js')
        ->appendFile($this->corePath() . '/js/jquery-extend.js')
        ->appendFile($this->corePath() . '/js/knockout-extend.js')
        ->appendFile($this->corePath() . '/js/admin/view_model.js')
        ->appendFile($this->corePath() . '/js/lib.js')
        ->appendFile($this->corePath() . '/js/admin/script.js')
    ."\n"
    ?>

    <script type="text/javascript">
        window.onload = function(){
            handleMenu();
        }
    </script>
</head>
<body>
    <div id="main">
        <div class="header">
            <div class="col-md-3" style="text-transform: uppercase; margin-top: 11px;">
                <a href="<?=$this->langUrl('admin/default')?>"><?=$this->translate('Admin panel')?></a>
            </div>
            <div class="col-md-9" style="padding-right: 0px;">
                <div class="col-md-12" style="text-align: right">
                    <?php if($auth->hasIdentity()):?>
                        <small><?=$this->translate('Logged as').' ['.$auth->getIdentity()->getUname()?>]</small>
                    <?php endif; ?>
                </div>
                <div class="col-md-2" style="float: right;width: 72px;">
                    <a href="<?=$this->langUrl('admin/default', ['controller' => 'log', 'action' => 'out'])?>"><?=$this->translate('Log out')?></a>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div id="menu">
            <ul>
                <li><a rel="subMenu0" href="Javascript:void(0)" ><?=$this->translate('Content')?> |</a>
                    <div id="subMenu0">
                        <a href="<?=$this->langUrl('admin/rest', ['controller' => 'category', 'action' => 'list'])?>"><?=$this->translate('Categories')?></a>
                        <a href="<?=$this->langUrl('admin/rest', ['controller' => 'listing', 'action' => 'list'])?>"><?=$this->translate('Pages')?></a>
                    </div>
                </li>
                <li><a rel="subMenu2" href="Javascript:void(0)"><?=$this->translate('Administration')?>&nbsp;|</a>
                    <div id="subMenu2">
                        <a href="<?=$this->langUrl('admin/rest', ['controller' => 'language', 'action' => 'list'])?>"><?=$this->translate('Languages')?></a>
                        <a href="<?=$this->langUrl('admin/rest', ['controller' => 'user', 'action'=>'list'])?>"><?=$this->translate('Users')?></a>
                        <a href="<?=$this->langUrl('admin/rest', [
                            'controller' => 'user',
                            'action' => 'list',
                        ], ['fragment' => 'edit/'.$auth->getIdentity()->getId()])?>"><?=$this->translate('Account settings')?></a>
                    </div>
                </li>
            </ul>
            <ul style="float:right;">
                <li class="lang">
                    <span class="text lang">
                        <?=$this->activeAdminLanguages?>
                    </span>
                </li>
            </ul>
        </div>
        <div class="container">
            <div class="messages">
                <?php foreach (array('error', 'success', 'info', 'default') as $namespace):
                    //check for error messages
                    $plugin = $this->flashMessenger()->getPluginFlashMessenger();
                    if($plugin->getCurrentErrorMessages()){
                        echo $this->flashMessenger()->renderCurrent($namespace, array('alert', 'alert-dismissible', 'alert-danger'));
                        $plugin->clearCurrentMessages('error');
                    }
                    $style = $namespace != 'error' ? array('alert', 'alert-dismissible', 'alert-'.$namespace) :
                        array('alert', 'alert-dismissible', 'alert-danger');
                    echo $this->flashMessenger()->render($namespace, $style);
                endforeach; ?>
            </div>
            <div class="messages" data-bind="visible: messages().length > 0">
                <div data-bind="foreach: messages">
                    <div data-bind="attr: {class: 'alert alert-dismissible alert-' + (type == 'error' ? 'danger' : type) + ' fade in' }">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <span data-bind="text: message"></span>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <?=$this->content?>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="clearfix"></div>
        <footer class="footer">
            &copy; <?=date('Y')?> <a href="https://github.com/veniva/zcms">ZCMS - A light weight CMS</a>, released under the <a target="_blank" href="http://www.gnu.org/licenses/gpl-3.0.en.html">GNU/GPL 3.0 licence</a>
        </footer>
        <div class="clearfix"></div>
    </div>
    <script type="text/javascript">
        ko.applyBindings(viewModel);
    </script>
</body>
</html>
