<?php use Application\Service\Invokable;

echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <?=$this->headTitle($this->meta_title ?: $this->translate('ZCSM - a lightweight Content Management System'))."\n"?>
    <?=$this->headMeta()
        ->appendName('description', $this->meta_description ?: $this->translate('A CMS based on ZendFramework'))
        ->appendName('keywords', $this->meta_keywords ?: $this->translate('ZCMS, CMS, content management system'))."\n"?>
    <?=$this->headLink()
        ->prependStylesheet($this->corePath() .'/css/style.css')
        ->prependStylesheet($this->corePath() .'/css/bootstrap-theme.min.css')
        ->prependStylesheet($this->corePath() . '/css/bootstrap.min.css')
    ?>

    <?=$this->headScript()
        ->prependFile($this->corePath() . '/js/bootstrap.min.js')
        ->prependFile($this->corePath() . '/js/jquery-2.1.4.min.js')
        ->appendFile($this->corePath() . '/js/jscript.js');
    ?>

</head>
<body>
<nav id="header" class="navbar">
    <div class="container">
        <div class="col-xs-2">
            <h3><a class="btn btn-default" href="<?=$this->langUrl('home/default')?>">ZCMS</a></h3>
        </div>
        <div class="col-xs-10" style="text-align: right;padding:10px;">
            <?=$this->activeLanguages?>
        </div>
    </div>
</nav>
<div id="main" class="container">
    <div id="main-content" style="border-left:1px solid #E1E1E1;border-right:1px solid #E1E1E1;">
        <div class="col-sm-3" style="margin-top: 20px;">
            <?=$this->mainMenu?>
            <!--custom pages-->
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title"><?=$this->translate('Information')?></h3>
                </div>
                <ul class="list-group">
                    <li class="list-group-item">
                        <a href="<?=$this->langUrl('home/default', ['controller' => 'customPage', 'action' => 'contact'])?>"><?=$this->translate('Contact')?></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-sm-9">
            <div class="messages">
                <?php foreach (array('error', 'success', 'info', 'default') as $namespace):
                    $flashMessages = $this->flashmessenger()->render($namespace);
                    $namespace = $namespace == 'error' ? 'danger' : $namespace;/*adjust bootstrap to ZF2*/
                    if (!empty($flashMessages)):?>
                        <div class="alert alert-<?= $namespace ?>">
                            <?= $flashMessages ?>
                        </div>
                    <?php endif;
                endforeach; ?>
            </div>
            <div class="content">
                <?=$this->content?>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<nav class="footer navbar">
    <div class="container">
        &copy; <?=date('Y')?> <a href="https://github.com/veniva/zcms">ZCMS - A light weight CMS</a>, released under the <a target="_blank" href="http://www.gnu.org/licenses/gpl-3.0.en.html">GNU/GPL 3.0 licence</a>
    </div>
</nav>
</body>
</html>