<div class="header_cont">
    <div class="title" data-bind="text: title()"></div>
    <div data-bind="visible: action() == 'list'" style="float:right;">
        <a type="button" href="#add" class="btn btn-primary btn-xs"><?=$this->translate('New')?></a>
        <button type="button" id="del_button" class="btn btn-primary btn-xs"><?=$this->translate('Delete')?></button>
    </div>
</div>
<div class="body_cont">
    <div data-bind="visible: action() == 'list'">
        <div class="filter">
            <label for="filter_category">Filter: </label>
            <?=$this->formSelect($this->selectCategory)?>
        </div>
        <form name="listings">
            <table class="list_table" width="100%" cellpadding="5" cellspacing="0">
                <thead>
                <tr>
                    <th style="width: 20px">#</th>
                    <th style="width: 20px">&nbsp;</th>
                    <th><?=$this->translate('Link Name')?></th>
                    <th style="width: 150px;"><?=$this->translate('Category')?></th>
                    <th style="width: 20px;"><?=$this->translate('Sort')?></th>
                    <th style="width: 20px;"><?=$this->translate('Action')?></th>
                </tr>
                </thead>
                <tbody data-bind="visible: hasRecords() === true, foreach: listData">
                <tr>
                    <td data-bind="text: id"></td>
                    <td><input type="checkbox" name="lid[]" data-bind="value: id" /></td>
                    <td><a data-bind="attr: {href: '#edit/'+id}, text: link"></a></td>
                    <td>
                        <span data-bind="foreach: {data: categories, as: 'category'}">
                            [<span data-bind="text: category.id"></span>] <span data-bind="text: category.title"></span>
                        </span>
                    </td>
                    <td data-bind="text: sort"></td>
                    <td>
                        <a class="img" data-bind="attr: {href: '#edit/'+id}">
                            <img src="<?=$this->corePath()?>/img/admin/edit.gif" title="<?=$this->translate('Edit')?>" />
                        </a>
                    </td>
                </tr>
                </tbody>

            </table>
        </form>
        <span data-bind="html: paginator"></span>
    </div>
    <!--edit/add action -->
    <span data-bind="if: action() == 'edit' || action() == 'add'">
        <span data-bind="dynamicHtml: form()"></span>
    </span>
</div>
<form name="form_delete" action="#delete" method="post">
    <div>
        <input type="hidden" name="ids" value="" />
        <input type="submit" name="submit_delete" data-bind="visible: false" />
    </div>
</form>
<span style="display:none" id="url"><?=$this->langUrl("admin/rest", ['controller' => 'listing'])?></span>
<script type="text/javascript" src="<?=$this->corePath()?>/js/admin/rest.js"></script>
<script type="text/javascript" src="<?=$this->corePath()?>/js/admin/listing.js"></script>
<script type="text/javascript">
    $('#del_button').click(function(){
        var elements = $(document.listings).find('input[name="lid[]"]');
        var values = [];
        elements.each(function(){
            if(this.checked == true){
                values.push(this.value);
            }
        });
        if(values.length){
            if(confirm('<?=$this->translate('Are you sure you want to delete these pages')?>?')){

                document.form_delete.elements['ids'].value = values;
                document.form_delete.elements['submit_delete'].click();
            }
        }else{
            alert('<?=$this->translate('You must choose at least one item to delete')?>');
        }

        return false;
    });
</script>
<script type="text/javascript" src="<?=$this->corePath()?>/js/admin/rest-call.js"></script>
<script type="text/javascript" src="<?=$this->corePath().'/js/admin/summernote/summernote.min.js'?>"></script>
<?php $locale = str_replace('_', '-', $this->locale);
if($locale != 'en-US'):?>
    <script type="text/javascript" src="<?=$this->corePath().'/js/admin/summernote/lang/summernote-'.$locale.'.js'?>"></script>
<?php endif; ?>
