<div class="bcrumb">
    <?=$this->breadcrumb()?>
</div>
<h2><?=$this->category_content->getTitle()?></h2>

<h3><?=$this->translate('Sub-categories')?>:</h3>
<section id="sub-categories">
    <?php foreach($this->sub_categories as $subCategory): ?>
        <a href="<?=$this->langUrl('category', ['alias' => urlencode($subCategory->getSingleCategoryContent($this->langID)->getAlias())])?>">
            <?=$subCategory->getSingleCategoryContent($this->langID)->getTitle()?>
        </a>
    <?php endforeach; ?>
</section>
<?php if(!count($this->sub_categories)){echo $this->translate('none');}?>

<h3><?=$this->translate('Pages')?>:</h3>
<section id="category-pages">
    <?php foreach($this->category->getListings() as $listing): ?>
        <a href="<?=$this->langUrl('page', ['alias' => urlencode($listing->getSingleListingContent($this->langID)->getAlias())])?>">
            <?=$listing->getSingleListingContent($this->langID)->getLink(); ?>
        </a>
    <?php endforeach; ?>
</section>
<?php if(!count($this->category->getListings())){echo $this->translate('none');}?>
<script type="text/javascript">
    function separate(selector){
        var subCategories = selector;
        var elements = subCategories.find('a');
        subCategories.html('');
        elements.each(function(index){
            if(this.tagName.toLowerCase() == 'a'){
                subCategories.append(this);
                if(index < (elements.length-1))
                    subCategories.append('<span style="color:grey; font-size:0.8em"> | </span>');
            }
        });
    }

    separate($('#sub-categories'));//decorate the sub categories with a separator
    separate($('#category-pages'));//decorate the pages with a separator
</script>