<?php
use Application\Service\Invokable\Misc;
$this->form->prepare();
?>
<div class="header_cont">
    <div class="title"><?=$this->translate($this->action." a category")?></div>
</div>
<div class="body_cont">
    <?=$this->form()->openTag($this->form)?>
    <table class="list_table" width="400" cellpadding="5" cellspacing="0">
        <?php foreach($this->form->get('content')->getFieldsets() as $fieldset):?>
            <tr>
                <td>
                    <?php if(!isset($labelled)): ?>
                        <label><?=$this->translate($this->form->get('content')->getFieldsets()[0]->getElements()['title']->getLabel())?>:</label>
                    <?php $labelled = true; endif; ?>
                </td>
                <td>
                    <?=$this->formInput($fieldset->getElements()['title'])?>
                    <?php $lang = $fieldset->getObject()->getLang()?>
                    <img src="<?=$this->basePath().'/img/flags/'.$lang->getIsoCode()?>.png" title="<?=$lang->getName()?>" />
                    <?php if($lang->isDefault()):?>(<?=$this->translate('default')?>)<?php endif; ?>
                    <div class="form-error">
                        <?=$this->formElementErrors($fieldset->getElements()['title'])?>
                    </div>
                </td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td><label><?=$this->translate($this->form->get('sort')->getLabel())?></label></td>
            <td>
                <?=$this->formInput($this->form->get('sort'))?>
                <div class="form-error">
                    <?=$this->formElementErrors($this->form->get('sort'))?>
                </div>
            </td>
        </tr>
        <tr>
            <td><?=$this->translate('Parent category')?>:</td>
            <td><?=($this->parentCategory instanceof \Application\Model\Entity\Category) ?
                    $this->parentCategory->getSingleCategoryContent()->getTitle() :
                    $this->translate('Top')?></td><!--v_todo - insert a category tree select input here-->
        </tr>
        <tr>
            <td colspan="2">
                <button class="btn btn-primary btn-xs" name="categ_form"><?=$this->translate('Submit')?></button>
                <small> <a href="<?=$this->langUrl('admin/category', [
                        'id' => isset($this->parentCategory) ? $this->parentCategory->getId() : null,
                        'page' => $this->page,
                    ])?>"><?=$this->translate('Cancel')?></a></small>
            </td>
        </tr>
    </table>
    <?=$this->form()->closeTag()?>
    <div style="height:100px;">&nbsp;</div>
</div>