<?php use Application\Service\Invokable\Layout; ?>
<div class="header_cont">
    <div class="title"><?=$this->translate($this->title)?></div>
    <div style="float:right;">
        <button type="button" id="add_button" class="btn btn-primary btn-xs"><?=$this->translate('New')?></button>
    </div>
</div>
<div class="body_cont">
    <div class="bcrumb lui-padding-5">
        <?=$this->breadcrumb()?>
    </div>
    <table class="list_table" width="100%" cellpadding="5" cellspacing="0">
        <tr>
            <th width="20">#</th>
            <th><?=$this->translate('Category')?></th>
            <th width="20"><?=$this->translate('Sort')?></th>
            <th width="70"><?=$this->translate('Action')?></th>
        </tr>
        <?php foreach($this->categories as $category): ?>
            <tr>
                <td><?php echo $category->getId(); ?></td>
                <td>
                    <a href="<?=$this->langUrl('admin/category', array('id' => $category->getId()))?>">
                        <?php echo $category->getSingleCategoryContent($this->defaultLangId)->getTitle(); ?>
                    </a>
                    <small><?='(' . $this->categoryRepo->countChildren($category->getId()) . ')'?></small>
                </td>
                <td>
                    <?=$category->getSort(); ?>
                </td>
                <td>
                    <a class="img" href="<?=$this->langUrl('admin/category', array(
                        'action' => 'edit',
                        'id' => $category->getId(),
                        'page' => $this->page,
                    ))?>">
                        <img src="<?=$this->basePath()?>/img/admin/edit.gif" title="<?=$this->translate('Edit')?>" />
                    </a>
                    <a class="img del_button" href="#" data-href="<?=$this->langUrl('admin/category', [
                        'action' => 'delete', 'id' => $category->getId(), 'page' => $this->page,
                    ])?>">
                        <img src="<?=$this->basePath()?>/img/admin/delete.gif" title="<?=$this->translate('Delete')?>" />
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <?=$this->paginationControl($this->categories, 'Sliding', 'paginator/sliding', [
        'route' => 'admin/category',
        'id' => $this->parent_id])?>
</div>
<script type="text/javascript">
    $('#add_button').click(function(){
        location.href='<?=$this->langUrl('admin/category', ['action' => 'add', 'id' => $this->parent_id, 'page' => $this->page,])?>';
    });
    $('.del_button').click(function(){
        if(confirm('<?=$this->translate('Are you sure you want to delete this category and all listings in it?')?>')){
            location.href=this.dataset.href;
        }
        return false;
    });
</script>