<?php use Application\Service\Invokable\Layout; ?>
<div class="header_cont">
    <div class="title"><?=$this->translate($this->title)?></div>
    <div style="float:right;">
        <button type="button" id="add_button" class="btn btn-primary btn-xs"><?=$this->translate('New')?></button>
    </div>
</div>
<div class="body_cont">
    <div class="bcrumb lui-padding-5">
        <?php if($crumb = Layout::breadcrumb($title, $this->category_alias)): ?>
            <?php $items = [];
            foreach($crumb as $item):?>
                <?php $items[] = !$item ?
                    '<a href="'.$this->langUrl('admin/category').'">'.$this->translate('Top').'</a>' :
                    '<a href="'.$this->langUrl('admin/category', ['id' => $item['id']]).'">'.$item['title'].'</a>'?>
            <?php endforeach; ?>
            <?=implode(' &gt; ', $items)?> &gt; <?=$title?>
        <?php else:?>
            <?=$this->translate('Top')?>
        <?php endif; ?>
    </div>
    <table class="list_table" width="100%" cellpadding="5" cellspacing="0">
        <tr>
            <th width="20">#</th>
            <th><?=$this->translate('Category')?></th>
            <th width="20"><?=$this->translate('Order')?></th>
            <th width="70"><?=$this->translate('Action')?></th>
        </tr>
        <?php foreach($this->categories as $category): ?>
            <tr>
                <td><?php echo $category->getId(); ?></td>
                <td>
                    <a href="<?=$this->langUrl('admin/category', array('id' => $category->getId()))?>">
                        <?php echo $category->getContent()->getTitle(); ?>
                    </a>
                    <small><?='(' . $category->getChildrenCount() . ')'?></small>
                </td>
                <td>
                    <?=$category->getSort(); ?>
<!--                    <a href="--><?php //echo link_url('order/order_categs/' . $cid.'/'.$type); ?><!--">-->
                    <a class="img" href="<?=$this->url('admin')?>">
                        <img src="<?=$this->basePath()?>/img/admin/reorder.png" title="<?=$this->translate('re-order')?>" />
                    </a>
                </td>
                <td>
                    <?php if ($category->getId() != 17): ?>
                        <a class="img" href="<?=$this->langUrl('admin/category', array(
                            'action' => 'edit',
                            'id' => $category->getId(),
                            'page' => $this->page,
                        ))?>">
                            <img src="<?=$this->basePath()?>/img/admin/edit.gif" title="<?=$this->translate('edit')?>" />
                        </a>
                        <a class="img del_button" href="#" data-href="<?=$this->langUrl('admin/category', [
                            'action' => 'delete', 'id' => $category->getId(), 'page' => $this->page,
                        ])?>">
                            <img src="<?=$this->basePath()?>/img/admin/delete.gif" title="<?=$this->translate('delete')?>" />
                        </a>
                    <?php else: ?>
                        <img src="<?=$this->basePath()?>/img/admin/lock.png" title="<?=$this->translate('locked')?>" />
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <?=$this->paginationControl($this->categories, 'Sliding', 'paginator/category_sliding', [
        'route' => 'admin/category',
        'id' => $this->parent_id])?>
</div>
<script type="text/javascript">
    $('#add_button').click(function(){
        location.href='<?=$this->langUrl('admin/category', ['action' => 'add', 'id' => $this->parent_id, 'page' => $this->page,])?>';
    });
    $('.del_button').click(function(){
        if(confirm('<?=$this->translate('Are you sure you want to delete this category and all listings in it')?>')){
            location.href=this.dataset.href;
        }
        return false;
    });
</script>