<div class="header_cont">
    <div class="title" data-bind="text: title"></div>
    <div data-bind="visible: action() == 'list'" style="float:right;">
        <a type="button" class="btn btn-primary btn-xs" data-bind="attr: {href: $root.url+'#add/'+parentID()+'/'+page()}">
            <?=$this->translate('New')?>
        </a>
    </div>
</div>
<div class="body_cont">
    <!-- list action -->
    <div data-bind="visible: action() == 'list'">
        <div class="bcrumb lui-padding-5">
        <span data-bind="html: breadcrumb">
        </div>
        <table class="list_table" width="100%" cellpadding="5" cellspacing="0">
            <thead>
            <tr>
                <th width="20">#</th>
                <th><?=$this->translate('Category')?></th>
                <th width="20"><?=$this->translate('Sort')?></th>
                <th width="70"><?=$this->translate('Action')?></th>
            </tr>
            </thead>
            <tbody data-bind="visible: hasRecords() === true, foreach: categoryData">
            <tr>
                <td data-bind="text: id"></td>
                <td>
                    <a data-bind="text: title, attr: {href: '#'+id+'/'+$root.page()}"></a>
                    <small data-bind="text: '('+children_count+')'"></small>
                </td>
                <td data-bind="text: sort"></td>
                <td>
                    <a class="img" data-bind="attr: {href: $root.url+'#edit/'+id+'/'+$root.page()}">
                        <img src="<?=$this->basePath()?>/img/admin/edit.gif" title="<?=$this->translate('Edit')?>" />
                    </a>
                    <a href="#" class="img del_button" data-bind="click: function(data, event){ clickDelete(id); }">
                        <img src="<?=$this->basePath()?>/img/admin/delete.gif" title="<?=$this->translate('Delete')?>" />
                    </a>
                    <form method="POST" data-bind="attr: {action: '#delete/'+id+'/'+$root.page()}">
                        <input type="hidden" name="id" data-bind="value: id" />
                        <input type="hidden" name="page" data-bind="value: $root.page()" />
                        <input type="submit" data-bind="attr: {id: 'del_'+id}, visible: false" />
                    </form>
                </td>
            </tr>
            </tbody>
            <tbody data-bind="visible: hasRecords() === false">
            <tr><td colspan="4"><?=$this->translate('No records found');//v_todo - translate?></td></tr>
            </tbody>
        </table>
        <span data-bind="html: paginator"></span>
    </div>

    <!--edit action -->
    <span data-bind="visible: action() == 'edit' || action() == 'add', html: form()"></span>

</div>

<div id="url" style="display:none"><?=$this->langUrl('admin/category')?></div>
<script src="<?=$this->basepath() . '/js/admin/category.js'?>"></script>

<script type="text/javascript">
    function clickDelete(id){
        if(confirm('<?=$this->translate('Are you sure you want to delete this category and all listings in it?')?>')){
            document.getElementById('del_'+id).click();
        }
        return false;
    }
</script>