<?php if($crumb = $this->breadcrumb): ?>
    <?php $items = [];
    foreach($crumb as $item):?>
        <?php $items[] = !$item ?
            '<a href="'.$this->langUrl('admin/rest', ['controller' => 'category', 'action' => 'list']).'">'.$this->translate('Top').'</a>' :
            '<a href="'.$this->langUrl('admin/rest', ['controller' => 'category'], ['fragment' => $item['id'].'/1']).'">'.$item['title'].'</a>'?>
    <?php endforeach; ?>
    <?=implode(' &gt; ', $items)?> &gt; <?=$this->title?>
<?php else:?>
<?=$this->translate('Top')?>
<?php endif; ?>