<div class="container">
    <div class="header_cont"><?=$this->translate('Dashboard')?></div>
    <div class="body_cont">
        <div class="icons">
            <a href="<?=$this->url('admin/category')?>" title="<?=$this->translate('Categories')?>">
                <img src="<?=$this->basePath()?>/img/admin/categories.png" alt="<?=$this->translate('Categories')?>" onMouseOver="img_change.ov(this, '<?=$this->basePath()?>/img/admin/categories');" onMouseOut="img_change.out(this);" border="0" />
            </a>
            <br />
            <?=$this->translate('Categories')?>
        </div>
        <div class="icons">
            <a href="<?=$this->url('admin/listing')?>" title="<?=$this->translate('Pages')?>">
                <img src="<?=$this->basePath()?>/img/admin/notepad.png" alt="<?=$this->translate('Pages')?>" onMouseOver="img_change.ov(this, '<?=$this->basePath()?>/img/admin/notepad');" onMouseOut="img_change.out(this);" border="0" />
            </a>
            <br />
            <?=$this->translate('Pages')?>
        </div>
        <div style="height:300px;">&nbsp;</div>
    </div>
</div>