<?php $this->layout('admin/login');//change the default layout to the login layout

$form  = $this->form;
$form->prepare();
$email = $form->get('email');
$email->setAttributes(['class' => 'form-control']);
$errors = $this->formElementErrors($email);
?>

<?php foreach (array('error', 'success', 'info', 'default') as $namespace):
    $flashMessages = $this->flashmessenger()->render($namespace);
    $namespace = $namespace == 'error' ? 'danger' : $namespace;/*adjust bootstrap to ZF2*/
    if (!empty($flashMessages)):?>
        <div class="alert alert-<?=$namespace?>" role="alert">
            <?= $flashMessages ?>
        </div>
    <?php endif;
endforeach; ?>
<?php if($errors):?>
    <div class="alert alert-danger" role="alert">
        <?=$errors?>
    </div>
<?php endif;?>

<div class="panel panel-default">
    <div class="panel-heading">
        <?=$this->translate('Reset password')?>
    </div>
    <div class="panel-body">
        <?=$this->form()->openTag($form)?>
        <div class="form-group">
            <label class="control-label col-md-4"><?=$this->translate($email->getLabel())?>:</label>
            <div class="col-md-8">
                <?=$this->formInput($email)?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-8 col-md-offset-4">
                <input class="btn btn-default" type="submit" name="submit" value="<?=$this->translate('Send link')?>" />
                <a class="btn btn-link forgotten_link" href="<?=$this->langUrl('admin/default', ['controller' => 'log', 'action' => 'in'])?>"><?=$this->translate('back to login')?></a>
            </div>
        </div>
    </div>

</div>